### ISSUE TITLE
Can we have btx back?

### ISSUE THREAD

**Issue by denisbr** [vegardinho/alfred_bluetooth_controller#10]
I super appreciate this addon, and have been using it every day since I found it. However removing btx was a bit of a downer for me, as I much prefer having a keyword in Alfred than Yet Another Hotkey Combo to remember.

Any chance you could consider reverting the removal? ❤️

**Comment by ams242** [comment]
I would appreciate btx too, it was my most used shortcut.

**Comment by vegardinho** [comment]
Some people argue there’s too many menus, that’s why I removed it. Personally I recall all keywords by memory, so a long list of options doesn’t bother me. If this is important to people, I have no problem adding it back again.

**Comment by denisbr** [comment]
I don't understand the "too many menus" thing, but this isn't really a big deal either. Feel free to close it.

**Comment by ams242** [comment]
> Some people argue there’s too many menus, that’s why I removed it. Personally I recall all keywords by memory, so a long list of options doesn’t bother me. If this is important to people, I have no problem adding it back again.

Hi, thanks for the quick reply, if it`s better, for most of the people, let it be removed, i fixed it for myself.

**Comment by vegardinho** [comment]
My philosophy in making this workflow is to include as much capability and features as possible, so I am actually inclined to include it back again. I've only had one complaint so far on the long list of commands, so if I don't get any more requests to keep things simple, I think I'll re-add it in the next release.
