### ISSUE TITLE
Macbook Air M1

### ISSUE THREAD

**Issue by gboaca** [vegardinho/alfred_bluetooth_controller#15]
When I try to run I get this:
![image](https://user-images.githubusercontent.com/59828580/133879765-0a455f06-b089-475b-b2a6-80f3f4dbed2d.png)

**Comment by gboaca** [comment]
After I rtfm I managed to find the command to fix this, but I get another error. When I do "Show package contents"  on Alfred.alfredpreferences it's blank...

![image](https://user-images.githubusercontent.com/59828580/133879945-f83690f9-539d-4570-8e10-8f541aa70866.png)

**Comment by gboaca** [comment]
I found out I have a custom install path, changed the path, all good now. Closed, tks :)

**Comment by vegardinho** [comment]
Glad you got it sorted out!
