### ISSUE TITLE
 can't close bluetooth in mac  Monterey

### ISSUE THREAD

**Issue by baixiaoyu2997** [vegardinho/alfred_bluetooth_controller#17]
evn
1. mac: Montery
1. alfred：4.6[1266]
2. bluetooth controller: 2.3.1

**Comment by vegardinho** [comment]
There is a known issue disconnecting with blueutil on Monterey (https://github.com/toy/blueutil/issues/58). If you want the quickest possible fix, notify me or do a pull request with the new binary, once a new version is released.

**Comment by baixiaoyu2997** [comment]
ok , thank you for your reply
