### ISSUE TITLE
Favorite Device - Auto connect?

### ISSUE THREAD

**Issue by allcentury** [vegardinho/alfred_bluetooth_controller#19]
Right now airpods seem to automatically connect to my phone when I'd rather it be my laptop.  Can favorites watch available devices and toggle on instead of manually needing to toggle?

**Comment by vegardinho** [comment]
I’m not sure I understand what you mean, but I doubt there’s much I can do
here. Your airpods connecting automatically is handled by the OS, and
should not require any additional software to do so. (And very unlikely
even possible with a workflow.)  I’m not familiar with airpods, but
generally bluetooth devices tend to connect to a preferred device, usually
the last one connected, thus hindering any automatic connection to any
other device. (Though I’m not really sure wether it’s the bluetooth device
or the device it’s connecting to that requests the connection.) I would
suggest you unpair them with your phone and mac, pair them again, first
with your mac, then your iphone.

That being said, pairing using the workflow has been buggy with my
headphones. They claim to be paired but won’t connect properly, and only
connect when paired the old fashioned way. Therefore, try pairing using the
default menu on the mac if you still have problems.

**Comment by allcentury** [comment]
@vegardinho sorry if my issue was missing details.  I have 5 apple devices in my office, 3 for work, 2 for personal use.  

I want to set a preferred device (work laptop) that my airpods connect to.  So I'm thinking the flow is, open airpods case (becomes bluetooth available).  If they are not connected to my worklaptop in some_time_interval, have this controller prompt me asking if it should connect.  If it already is connected, do nothing.  

I see that as:

1. repeated task to watch devices available and connected
2. connection prompt when not (sleep or mute by user's preference)

Apple has this somewhat built in, via [connect to last device](https://www.macrumors.com/how-to/stop-airpods-connecting-to-other-devices/) but i'm having mixed experience with it.

**Comment by vegardinho** [comment]
I still stand by my last comment that this is beyond the scope of the
workflow, and that i doubt this is even possible to implement with an
alfred workflow. I understand the frustration though, bluetooth has caused
me more than a fair share of trouble over the years as well.

**Comment by allcentury** [comment]
Thanks for chatting through it, I'll close.
