### ISSUE TITLE
New Command: btr

### ISSUE THREAD

**Issue by warthurton** [vegardinho/alfred_bluetooth_controller#2]
I can put up a pull request, but I created another keyword: btr
Bluetooth Reset

Same as the toggle but toggles on/off/on or off/on/off.  Occasionally useful for really old devices to find the MacBook again.

I supposed you don't really need to handle off/on/off but this way no special case needs to be handled.

```
/usr/local/bin/blueutil --power toggle
sleep 1.5
/usr/local/bin/blueutil --power toggle
echo -n $(/usr/local/bin/blueutil --power)
```

**Comment by vegardinho** [comment]
I've included it manually now in the alfred project file. I should do some cleaning up of scripts, so i might eventually merge the alfred-only-scripts in a more git-friendly one, in the project folder.
