### ISSUE TITLE
MacOS Monterey 12.3 breaks the workflow

### ISSUE THREAD

**Issue by denisbr** [vegardinho/alfred_bluetooth_controller#21]
I've raised PR #20 which tries to make it work again, but haven't had time to do very thorough checking.
Hope it will help you fix the compatibility faster anyway :)

**Comment by vegardinho** [comment]
Thanks, but it is likely to break on older OS (see #1). I don't have too much experience with python cross compatibility, so I'll gladly receive any help on this one.
