### ISSUE TITLE
Command for removing a device from the paired bluetooth list

### ISSUE THREAD

**Issue by soumilgurjar** [vegardinho/alfred_bluetooth_controller#24]
I am wondering if it is possible to add a command (btremove) which would remove a formerly paired device from the bluetooth list. This would be different from the existing disconnect/toggle command. I couldn't find any command for it currently.

In my case, I need it because my split bluetooth keyboard (using nice!nanos) does not play well with macOS bluetooth and does not auto-reconnect after entering in range. So I need to remove the device from the paired list and reconnect it again. It would be great if I am able to set up a hotkey which does btremove +  wait + btpair for my favourite device.

Thanks for any suggestions or clarifications.

**Comment by vegardinho** [comment]
Added with a961ffd16292ea554dcf2b23c9505117e997f04b and 7e95512b3e0a0b1b314ce1eefe6ac91d6b41ce1e
