### ISSUE TITLE
blueutil path is potentially different on 12.4

### ISSUE THREAD

**Issue by abondarev84** [vegardinho/alfred_bluetooth_controller#25]
my path on 12.4 is `/Users/<username>/.config/alfred/Alfred.alfredpreferences/workflows/user.workflow.*/blueutil`

consider using `$HOME/.config/alfred/Alfred.alfredpreferences/workflows/user.workflow.*/blueutil` in your instructions to be a bit more generalized?

**Comment by vegardinho** [comment]
Are you having issues with this as of now? Could you in that case post some debugging info? Currently I use relative paths, i.e. './blueutil', so I am a little surprised if if does not work for you, even with a different workflow path.

**Comment by abondarev84** [comment]
once I adjusted the path it was smooth scrolling from there.

**Comment by vegardinho** [comment]
Where did you adjust the path?

**Comment by vegardinho** [comment]
Never mind, I understood what you meant now. Your path does not work for me, so for now I propose to point to whatever the alfred gui spits out: bd8a8cb5ff46ac8666f523c4ed2395d9dba748b3

**Comment by abondarev84** [comment]
I'm on 12.4 on a managed laptop if that helps.
but I totally agree, my path might be completely different to others.

I'm not sure if it's possible but maybe the path can be populated during "install" based on pwd of the workflow?

**Comment by vegardinho** [comment]
Unless you have a concrete suggestion, I'll go ahead and merge #26.
