### ISSUE TITLE
btx-command does not exist

### ISSUE THREAD

**Issue by wuesten-fuchs** [vegardinho/alfred_bluetooth_controller#28]
When I set a new bluetooth device as my favorite I get the following notification:
Favorite device set to XXX
Use "btx" to connect to this device directly

But this command does not exist

**Comment by vegardinho** [comment]
Thanks for pointing out the bug!

Fixed by [v3.0.3](https://github.com/vegardinho/alfred_bluetooth_controller/releases/tag/3.0.3).

**Comment by wuesten-fuchs** [comment]
Wow, that was quick. Thank you!

At least on my machine, the cmd + ctrl + alt + f hotkey does not work / does nothing.

**Comment by vegardinho** [comment]
Hmm, that's not an issue with me, so it might be specific to your software. I'll have to know whether this is a common issue/if the hotkey is hardcoded into macOS/hardware before considering changing it.

In the meantime you can always change the hotkey manually.
