### ISSUE TITLE
disconnect device does not work.

### ISSUE THREAD

**Issue by danielman111** [vegardinho/alfred_bluetooth_controller#29]

**Comment by vegardinho** [comment]
That's not a problem I'm experiencing. If you want me to look into it, you have to post some debugging information.

**Comment by swapnilsm** [comment]
I am also facing the same issue.  I am on Monterey 12.6. 
I debugged it a bit and found that using the following command to disconnect works. 

`blueutil --disconnect {uid} --wait-disconnect {uid}`

**Comment by vegardinho** [comment]
Thanks for fix, @swapnilsm! New release out now.
