### ISSUE TITLE
Manage favorites

### ISSUE THREAD

**Issue by JoacimSchwartz** [vegardinho/alfred_bluetooth_controller#34]
What do you do if you no longer wish to have devices as 'Favorite'? I do not see any way to manage or edit the list to remove the star icon of a certain device.

**Comment by vegardinho** [comment]
You are quite correct that there is no possibility of removing favorites as of now. Should be quite easy to add, but since the workflow is broken on my mac (see #33), I'm not able to implement anything at the moment.

**Comment by vegardinho** [comment]
Closed by [release 4.0](https://github.com/vegardinho/alfred_bluetooth_controller/releases/tag/4.0).
