### ISSUE TITLE
macOS Sonoma 14 can not use this workflow

### ISSUE THREAD

**Issue by gan1235188** [vegardinho/alfred_bluetooth_controller#36]
when I update my macOS to Sonoma 14. I can not use this workflow. 

solution: add the bluetooth permission to Alfred in System setting -> security -> bluetooth.

![image](https://github.com/vegardinho/alfred_bluetooth_controller/assets/8969447/c5fa4a34-12c8-4c60-b80e-8eb673245319)

**Comment by gan1235188** [comment]
can we update this to readme?

**Comment by vegardinho** [comment]
Added to README 7539afc40b3daea3e5e3fdb8c9b56cfd8cee5ba8.
