### ISSUE TITLE
Remote Triggers

### ISSUE THREAD

**Issue by chrisgrieser** [vegardinho/alfred_bluetooth_controller#4]
makes a lot of sense, if you connect a TV to your Mac and e.g. play games on the big screen. Pairing Controllers etc could be useful to do from the Alfred remote app.

**Comment by vegardinho** [comment]
As I'm not using the remote app myself (I haven't even bought it), it is a bit unpractical for me to develop/test this out. However, if you would add this to you own version of the workflow and send it to me, I would be happy to make a new release with the new features!

**Comment by chrisgrieser** [comment]
Here is the workflow with the changes. I added Remote Triggers to everything,  changed `bt` to `btt` as you suggested yourself, and added a bluetooth status overview (I made it for myself, but it fits your workflow, too – feel free to add it, improve it, or leave it out.)

Everything I changed or made is colored in light blue. 

https://drive.google.com/file/d/1nCraAsrPzTX3Ceo93lxQTJQAAQ4VitJX/view?usp=sharing

**Comment by vegardinho** [comment]
Now included in 37672da3ae175d58503d9742224c5fe7d743b865 / [release v2.0](https://github.com/vegardinho/alfred_bluetooth_controller/releases/tag/2.0)!

**Comment by vegardinho** [comment]
I realize I haven't added the remote capability to readme. Since I haven't used or will use this myself, I would really appreciate it if you could do a pull request on it!:)

**Comment by chrisgrieser** [comment]
thanks for the honor :)

**Comment by vegardinho** [comment]
No worries, just happy to get some help;)
