### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by chrisgrieser** [vegardinho/alfred_bluetooth_controller#5]
I know its minor, but a keyword to reset bluetooth, instead of turning on and off would be useful for connection trouble. Basically:

`blueutil -p 0 && sleep 1 && blueutil -p 1`

to save some space, you could remove the bluetooth on and off functionality - Reset & toggle should be enough (with info on the toggle whether bluetooth is on or off)

**Comment by vegardinho** [comment]
Hi, this is already implemented through the `btr` (reset; see #2) and `bt`(toggle) keywords. I find it best to to keep the `bton` and `btoff` keywords, as they are useful when you want to make sure you have turned bluetooth on/off.

A change I will probably make in an upcoming release though, is change the keyword for toggle from `bt`to `btt`. That way it's much easier to search up, as it is differentiated from the other keywords.
