### ISSUE TITLE
btr & btstatus

### ISSUE THREAD

**Issue by chrisgrieser** [vegardinho/alfred_bluetooth_controller#7]
https://github.com/vegardinho/alfred_bluetooth_controller/issues/5#issuecomment-839193542

you mention a `btr` command which is also mentioned in the documentation, but nowhere to be found in the actual workflow. ;)

Also, you left the btstatus command in there without mentioning it in release notes and read.me

**Comment by vegardinho** [comment]
Pretty sure there's no `btr` mentioned in the documentation, at least not in read.me.

Can add the bit about btstatus.

**Comment by vegardinho** [comment]
Seems I deleted btr by accident on version 2.0. Have readded now, will be in new release in not too long.
